language: python

services:
  - docker

install:
  - pip install -r tests/requirements.txt

before_install:
  - docker-compose -f site/docker-compose.yml up --build -d
  - docker-compose -f SQLInjection/docker-compose.yml up --build -d

script:
  - pytest