version: '3'

services:
  db:
    container_name: chaimtube_db
    build: db/.
    env_file:
      - db/db.env
    networks:
      - project
    restart: always
  
  app:
    container_name: chaimtube_app
    build: app/.
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      - project
    restart: always

networks:
  project: