version: '3'

services:
  database:
    image: mariadb 
    volumes:
      - db:/var/lib/mysql
      - ./database_info.sql:/docker-entrypoint-initdb.d/database_info.sql
    env_file:
      - ./db.env
  
  website:
    image: httpd:latest
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html
    ports:
      - 80:80

volumes:
  db:
